### ISSUE TITLE
Unable to connect launch remote desktop

### ISSUE THREAD

**Issue by dwkimtech** [rcktrncn/taskt#1]
Hello, 
Thank you for updating the taskt uob. 

I'm experiencing issues accessing the remote desktop using " launch remote desktop"

When inserting the hostname , I attempted to use the IP address and port (e.g., 10.2.2.1:1000), but it didn't work.

I successfully accessed by starting the application "mstsc" and entering the key ID and password. 

However, I can't access applications inside Windows in mstsc(ex. Cmd, IE) and couldn't find a list of windows and try to use "current windows" menu work also not working when trying to add "key/mouse commands"

One more thing, "remote commands-remot task"
I think this command like putty functions but no input menu ID and PW fields.

Could you please help me with resolving this issue?

**Comment by rcktrncn** [comment]
Hi! Thanks for providing the information about the problem.
Sorry, I don't have the environment to run remote desktop at the moment, so it will take some time to fix it.

**Comment by rcktrncn** [comment]
Hi!
It took me a while, but the problem of not being able to connect with the Launch Remote Desktop command has been resolved in v3.5.2.3.

**Comment by dwkimtech** [comment]
Hi
Thank you vary much for fixing taskt
Great job

2024년 8월 4일 (일) 오후 4:55, rcktrncn ***@***.***>님이 작성:

**Comment by rcktrncn** [comment]
Hi, the remote desktop screen displayed by mstsc or taskt's Remote Desktop command is similar to a video like WebCamera.
Therefore, we are currently unable to get the remote desktop window name or recognize buttons with the UIAutomation commands.
When using taskt to control a remote desktop, you can only use keyboard operation with the Enter Keys command or image recognition with the 'Image Recognition' command.
Or execute taskt on the remote desktop computer.

**Comment by dwkimtech** [comment]
Hi, I tried sending the Enter keys command to a remote desktop, but it
isn't working on Windows 2008 and Windows 10. The command only works on the
local taskt computer.

2024년 8월 7일 (수) 오후 8:21, rcktrncn ***@***.***>님이 작성:

**Comment by rcktrncn** [comment]
Hello! Please try to change the keyboard settings listed on this page or change the Keyboard Hook Mode in the Launch Remote Dekstop command.
URL: https://www.nextofwindows.com/how-to-use-the-same-win-key-combinations-on-remote-desktop
![keyboard_hook_mode](https://github.com/user-attachments/assets/06eb6508-1bfa-46cd-93a3-040d7a7b31d0)

**Comment by rcktrncn** [comment]
After changing the keyboard settings, the Windows key does not work with the Enter Keys command.
In that case, Ctrl+ESC will cause the Windows key to be pressed, as in the sample below.

After downloading, please change the extension from txt to xml.
[Launch_Remote_Desktop_sample.txt](https://github.com/user-attachments/files/16643036/Launch_Remote_Desktop_sample.txt)

**Comment by rcktrncn** [comment]
Remote Task command calls the LocalListener API; check the sample from v3.5.2.14 or later.
Remote Task command has been changed to **Call LocalListener API** command after v3.5.2.14.
