### ISSUE TITLE
Mouse move slow/broken since v3.5.1.40

### ISSUE THREAD

**Issue by z1ad** [rcktrncn/taskt#2]
Hello, first of all thank you for this fork + adding so much additional functionality!

Ive recorded a very simple script (move mouse around in a circle) and when playing it back, the mouse moves very slowly. So a 1-2 second script can take 1-2 minutes to run.

Downgrading to version v3.5.1.39 fixes the problem for now but I would love to be able to use the latest version :-)

**Comment by rcktrncn** [comment]
Hi! Thanks for providing the information about the problem.
That problem has been fixed in v3.5.1.69
