### ISSUE TITLE
Taskt hangs when GUI element does not exist

### ISSUE THREAD

**Issue by NinjaScareCrow** [rcktrncn/taskt#4]
Using an if command, there are a number of commands that need to take place if a GUI element exists. If it does not exist, then naturally the if should not be entered, and the rest of the script should process as per normal.

Everything works fine when the GUI element exists, but Taskt just sits on the line (20 in this case) and does nothing when the GUI element does not exist.

Screenshot 1 is the if configuration, and screenshot 2 is Taskt not processing any further once the if statement has been reached.

![Screenshot 2024-02-20 130233](https://github.com/rcktrncn/taskt/assets/20968542/7a0f3831-eb36-4302-bc55-1f8eecec115a)
![Screenshot 2024-02-20 131013](https://github.com/rcktrncn/taskt/assets/20968542/5d4116e8-59bc-4190-a2d5-a4783e0794a2)

**Comment by rcktrncn** [comment]
Hi! Thanks for the information about the bug.
Changed the process of searching for UIElement and fixed it so that it does not hang up.
Please try v3.5.1.84 or later.
