### ISSUE TITLE
How to run task in unattended mode

### ISSUE THREAD

**Issue by janardhancr1** [rcktrncn/taskt#5]
I abled to create RDP task workflow using Taskt and this is working well without user interaction in active session.
BUT I am struggling to configure it unattended mode. It means once I minimised or disconnect RDP and it throws "Access is denied" error.

I get this Error: "System.ComponentModel.Win32Exception (0x80004005): Access is denied" on UI automation or send keystrokes

**Comment by rcktrncn** [comment]
Hi, here is the UiPath documentation, try changing the registry as described here.

https://docs.uipath.com/robot/standalone/2023.4/user-guide/executing-tasks-in-a-minimized-rdp-window
